"""файл с данными"""
FPS = 60
MENU_FONT = 'arial'
GAMENAME = 'Nikita survive'
PATH =  [['assets/enemy-1.png', 'assets/enemy-2.png', 'assets/enemy-3.png'], ['assets/enemy-4.png', 'assets/enemy-5.png', 'assets/enemy-6.png'], ['assets/enemy-7.png', 'assets/enemy-8.png', 'assets/enemy-9.png']]
LVLUPS = 'assets/lvlups.png'
COLLIDE_MAP = 'collide_map.csv'
START_MENU = 'assets/menubg.png'
LOSE_MENU = 'assets/menu2.png'
WIN_MENU = 'assets/menu3.png'
MAP_LEVEL = 'assets/1level.png'
PLAYER_SPRITES = 'assets/player.png'
WIN_TIME = 10
WIDTH = 1200
HEIGHT = 900
RED = (255, 0, 0)
BLUE = (0, 0, 255)
YELLOW = (255, 255, 0)
GREEN = (0, 255, 0)
MAGENTA = (255, 0, 255)
CYAN = (0, 255, 255)
BLACK = (0, 0, 0)
WHITE = (255,255,255)
COLORS = [RED, BLUE, YELLOW, GREEN, MAGENTA, CYAN]